[package]
name = "boilerplate-api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
diesel = { version = "2.2.8", features = ["postgres", "r2d2"] }
r2d2 = "0.8.10"
r2d2_redis = "0.14.0"